# Generated by Django 4.1.6 on 2023-11-17 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_origin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(max_length=6, null=True, verbose_name='Referral Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
