# Generated by Django 4.1.6 on 2023-11-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_origin_app', '0003_alter_user_document_back_alter_user_document_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Referral Code'),
        ),
    ]
