# Generated by Django 5.0.3 on 2024-03-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_origin_app', '0004_alter_user_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='document_back',
        ),
        migrations.RemoveField(
            model_name='user',
            name='document_front',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referred_users',
        ),
    ]
